//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XposLIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sampler
    {
        public int SamplerID { get; set; }
        public string IDNumb { get; set; }
        public string SamplerName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
